[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%LZ

[PARSER]
    Name          ros1_line
    Format        regex
    Regex         ^\[(?<level>INFO|WARN|ERROR|DEBUG|FATAL)\] \[(?<timestamp>[\d.]+)\]: (?<message>.+)$
    Time_Key      timestamp
    Time_Format   %s.%L

[PARSER]
    Name          ros2_humble_line
    Format        regex
    Regex         ^\[(?<level>INFO|WARN|ERROR|DEBUG|FATAL)\] \[(?<timestamp>[\d.]+)\] \[(?<node>[^\]]+)\]: (?<message>.+)$
    Time_Key      timestamp
    Time_Format   %s.%L

[MULTILINE_PARSER]
    Name          ros2_humble
    Type          regex
    Flush_Timeout 2000
    Rule          "start_state"  "^\[(?:INFO|WARN|ERROR|DEBUG|FATAL)\]"  "ros2_cont"
    Rule          "ros2_cont"    "^(?!\[(?:INFO|WARN|ERROR|DEBUG|FATAL)\])"  "ros2_cont"